### ISSUE TITLE
If the width of the terminal is > 200, airshell fails to write the prompt correctly

### ISSUE THREAD

**Issue by bcwise** [robik/airshell#1]
If you increase the width of the terminal to greater than 200 characters, spaces are added in before the prompt.

I have fixed it with the following:

--- airshell.bash.0     2015-02-27 07:16:25.411530529 -0700
+++ airshell.bash       2016-10-04 08:46:15.602294014 -0600
@@ -152,12 +152,14 @@
 ash_fill_row()
 {
##      local cols=$(tput cols)
-    printf "cols: ($cols)"
  +
   printf "\e[48;${1}m" # Header BG
   for ((i=0;i<$cols;i++)); do
       printf " "
   done
-    printf "\e[199D"
-    # Now that you've written the line, back up to the beginning.
-    printf "\e[%sD" "$cols"
  }
  
  ash_build_left_side()

**Comment by robik** [comment]
Fixed, thanks!
